### ISSUE TITLE
Set input weights into a TRN model - Transfer Learning

### ISSUE THREAD

**Issue by rcervinoucm** [ctlearn-project/ctlearn#210]
**Describe the bug**
I am traying to set a weight set as input for a TRN model a TRN model, and I am getting this error:

pd.DataFrame(
/home/rcervino/anaconda3/envs/mrkrabs2/lib/python3.10/site-packages/dl1_data_handler/reader.py:818: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_items] [items->None] pd.DataFrame(
INFO: Number of events loaded: 2810246
INFO:Setting up model:
INFO: Constructing model from config.
Traceback (most recent call last):
 File "/home/rcervino/anaconda3/envs/mrkrabs2/bin/ctlearn", line 8, in <module>
  sys.exit(main())
 File "/home/rcervino/anaconda3/envs/mrkrabs2/lib/python3.10/site-packages/ctlearn/run_model.py", line 691, in main
  run_model(config, mode="train", debug=args.debug, log_to_file=args.log_to_file, save_best_only= args.save_best_only)
 File "/home/rcervino/anaconda3/envs/mrkrabs2/lib/python3.10/site-packages/ctlearn/run_model.py", line 178, in run_model
  backbone, backbone_inputs = backbone_model(data, model_params)
 File "/home/rcervino/anaconda3/envs/mrkrabs2/lib/python3.10/site-packages/ctlearn/default_models/single_cnn.py", line 123, in single_cnn_model
  return singlecnn_model, network_input
UnboundLocalError: local variable 'singlecnn_model' referenced before assignment

**To Reproduce**
1. Use a weight set as input - Command like: ctlearn -r type -w /data2/datasets/mrkrabs/Training/30.390_az_266.360/particletype/ -d TRN --num_epochs 15 --clean --input /data2/datasets/mrkrabs/TrainingDataMC/ --pattern "*" --tel_types LST_LST_LSTCam --size_cut 50 --output .

**Comment by TjarkMiener** [comment]
Thanks for reporting @rcervinoucm. I think it would be matter for renaming `model` to `singlecnn_model` [here](https://github.com/ctlearn-project/ctlearn/blob/master/ctlearn/default_models/single_cnn.py#L26-L27). Can you please take care of it?

**Comment by TjarkMiener** [comment]
I just checked, I think `loaded_model` needs to be renamed to  `singlecnn_model`.

**Comment by rcervinoucm** [comment]
I have to change loaded_model and model?

**Comment by rcervinoucm** [comment]
I solved locally and in the branch issue210, haven't made a pull request because I was locally testing. Do you think I should remove the branch and wait until de API deployment?
