### ISSUE TITLE
DivisionByZeroError in `apply_cuts` during `HDF5DataLoader` initialization

### ISSUE THREAD

**Issue by Jsevillamol** [ctlearn-project/ctlearn#52]
Configuration file of the run:
[20180905_231431_config.txt](https://github.com/ctlearn-project/ctlearn/files/2354601/20180905_231431_config.txt)

(it's actually a `.yml` file, but I had to change the extension to upload it)

List of example files used (they are part of the benchmark):
[sample_files.txt](https://github.com/ctlearn-project/ctlearn/files/2354604/sample_files.txt)

Traceback:
```
Traceback (most recent call last):
  File "/home/jsevillamol/Documentos/ctlearn_clean/ctlearn/run_model.py", line 459, in <module>
    run_model(config, mode=args.mode, debug=args.debug, log_to_file=args.log_to_file)
  File "/home/jsevillamol/Documentos/ctlearn_clean/ctlearn/run_model.py", line 130, in run_model
    **data_loading_settings)
  File "/home/jsevillamol/anaconda3/envs/ctlearn/lib/python3.6/site-packages/ctlearn/data_loading.py", line 136, in __init__
    self._apply_cuts()
  File "/home/jsevillamol/anaconda3/envs/ctlearn/lib/python3.6/site-packages/ctlearn/data_loading.py", line 536, in _apply_cuts
    self.class_weights.append(num_examples/float(self.passing_num_examples_by_particle_id[particle_id]))
ZeroDivisionError: float division by zero
Closing remaining open files:/home/jsevillamol/Documentos/datasample/gamma_20deg_0deg_srun103-219___cta-prod3_desert-2150m-Paranal-HB9_cone10.h5...done/home/jsevillamol/Documentos/datasample/proton_20deg_0deg_srun1-10___cta-prod3_desert-2150m-Paranal-HB9.h5...done
```

You can replicate it also just running this:
```
data_files = ['/home/jsevillamol/Documentos/ctlearn/datasample/gamma_20deg_0deg_srun103-219___cta-prod3_desert-2150m-Paranal-HB9_cone10.h5', '/home/jsevillamol/Documentos/ctlearn/datasample/proton_20deg_0deg_srun1-10___cta-prod3_desert-2150m-Paranal-HB9.h5']
image_mapping_settings = {'hex_conversion_algorithm': 'oversampling', 'padding': {'LST': 2, 'MSTF': 1, 'MSTN': 2, 'MSTS': 4, 'SST1': 1, 'SSTA': 0, 'SSTC': 0, 'VTS': 1}}
data_loading_settings = {'cut_condition': '(mc_energy > 1.0) & (h_first_int < 20000)', 'example_type': 'array', 'min_num_tels': 1, 'seed': 1234, 'selected_tel_ids': [1, 2, 3, 4], 'selected_tel_type': 'LST', 'validation_split': 0.1}
    
data_loader = HDF5DataLoader(
            data_files,
            mode='train',
            image_mapper=ImageMapper(**image_mapping_settings),
            **data_loading_settings)
```

(change `data_files` to whichever location has the relevant files)

**Comment by Jsevillamol** [comment]
Oh duh, its because none of the examples pass the filter

**Comment by Jsevillamol** [comment]
NVM, I have tried changing the `cut_condition` in the configuration to `(mc_energy > 0.0)` (which I assume it is a trivial condition to pass) and the problem persists.

**Comment by aribrill** [comment]
The bug seems to have been due to unnecessarily converting the iterator over rows in the table into a list, which exhausted the iterator. I've fixed that line and the example code runs now. In the above example, you can call `print(data_loader.passing_num_examples_by_particle_id)` to confirm the number of events passing the cuts matches the expected number.
